# Generated by Django 5.2.3 on 2025-07-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_adress2',
            new_name='shipping_fullname',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_full_name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
