# Generated by Django 5.2.3 on 2025-07-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_shipping_adress2_shippingaddress_shipping_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
